### PR TITLE
Language files update

### PR DESCRIPTION
**Pull request by kirancheema**
Added <languages></languages> to foo.xml as noticed they were not installing properly from the boilerplate component

### CODE REVIEW

**Comment by roland-d** [comment]
Hello,

Thank you for your contribution.

The language folders are not in the XML file on purpose. By leaving them out, the language files stay with the component. Joomla also searches the component folder for language files.

The changes in the language file look OK.

**Comment by kirancheema** [comment]
Ah Great ! 
that makes sense and much easier for development to keep all the files in the same place!
so it was probably just the missing language keys that threw me when i was trying out the boilerplate!

**Comment by roland-d** [comment]
@kirancheema That might very well be the case. Indeed we would like to keep all the files together. Can you update your PR and remove the XML changes?

**Comment by kirancheema** [comment]
Hi Roland  I think this should be done now?

**Comment by roland-d** [comment]
@kirancheema Yes, I think it is done now, so I have merged it. Thank you for your contribution.

**Pull request merged**
